import "./style.css";
import { BudokonClient } from "./api/budokon";
import { STAT_KEYS, type Judoka, type StatKey } from "./api/types";
import { createMatch, nextRound, selectStat, type GameMode, type Match, type RoundResult } from "./game/game";

const labels: Record<StatKey, string> = { power: "Power", speed: "Speed", technique: "Technique", kumikata: "Kumi-kata", newaza: "Ne-waza" };
const lengths = [3, 5, 10] as const;
const weights = ["-48", "-52", "-57", "-60", "-63", "-66", "-70", "-73", "-78", "-81", "-90", "-100", "+78", "+100"] as const;
type Division = "absolute" | "weight";
type History = Pick<RoundResult, "outcome" | "stat"> & { round: number };
const app = document.querySelector<HTMLDivElement>("#app");
if (!app) throw new Error("Application root is missing");
const root = app;
const client = new BudokonClient();
let match: Match | null = null, result: RoundResult | null = null, pendingStat: StatKey | null = null;
let seed = localStorage.getItem("judokon.seed") ?? "", activeSeed = "", activeWeight: string | undefined;
let target = 3, lengthIndex = 0, busy = false, errorMessage = "", history: History[] = [];
let division: Division = localStorage.getItem("judokon.divisionMode") === "weight" ? "weight" : "absolute";
let mode: GameMode = localStorage.getItem("judokon.gameMode") === "champion" ? "champion" : "classic";
let weight = localStorage.getItem("judokon.weightClass") ?? "random";
let soundEnabled = localStorage.getItem("judokon.soundEnabled") === "true";
let audioContext: AudioContext | null = null;

const esc = (value: string) => { const e = document.createElement("span"); e.textContent = value; return e.innerHTML; };
const nameOf = (j: Judoka) => `${j.firstname} ${j.surname}`;
const detailOf = (j: Judoka) => `${j.country} · ${j.weightClass} kg`;
const divisionLabel = () => division === "absolute" ? "Absolute" : weight === "random" ? "Random weight" : `${weight} kg`;
const modeLabel = () => mode === "champion" ? "Champion" : "Top Trumps";
function persist(): void { if (seed) localStorage.setItem("judokon.seed", seed); else localStorage.removeItem("judokon.seed"); localStorage.setItem("judokon.divisionMode", division); localStorage.setItem("judokon.gameMode", mode); localStorage.setItem("judokon.weightClass", weight); }
function status(): string {
  if (busy) return ">> Drawing judoka…"; if (errorMessage) return `>> ${errorMessage}`; if (!match) return ">> Configure a division and select a match length.";
  if (pendingStat) return ">> Opponent commits…"; if (match.phase === "selecting") return ">> Choose your stat:";
  if (match.phase === "matchOver") return `>> ${match.winner === "draw" ? "Match drawn." : match.winner === "player" ? "You win the match!" : "Opponent wins the match."}`;
  if (!result) return ">> Round resolved."; return `>> ${result.outcome === "draw" ? "Round drawn" : result.outcome === "player" ? "You win the round" : "Opponent wins the round"}: ${labels[result.stat]} ${result.playerValue}–${result.opponentValue}.`;
}
function fighter(j: Judoka, side: "player" | "opponent", comparison = result): string {
  const label = side === "player" ? "Your judoka" : "Opponent", value = comparison ? side === "player" ? comparison.playerValue : comparison.opponentValue : null;
  const chosen = comparison ? `<p class="selected-stat outcome-${comparison.outcome}"><span>${labels[comparison.stat]}</span><strong>${value}</strong></p>` : "";
  const rarity = j.rarity || "Unclassified";
  return `<section class="fighter-card ${side}" aria-label="${label}: ${esc(nameOf(j))}"><p class="eyebrow">${label}</p><h2>${esc(nameOf(j))}</h2><p>${esc(detailOf(j))}</p>${chosen}<span class="rarity rarity-${esc(rarity.toLowerCase())}">${esc(rarity)}</span></section>`;
}
function advanced(): string { return `<details class="advanced"><summary><span>Advanced</span><span class="disclosure-state">Show</span></summary><p>Use a seed only to replay a specific matchup. Leave it blank for a fresh match.</p><label for="seed">Replay seed <input id="seed" aria-label="Replay seed" autocomplete="off" value="${esc(seed)}" /></label><label class="sound-toggle"><input id="sound-enabled" type="checkbox" ${soundEnabled ? "checked" : ""} /> Keyboard ticks and outcome beeps <span>Muted by default</span></label></details>`; }
function launch(): string {
  const select = lengths.map((n, i) => `<button data-length="${n}" aria-pressed="${lengthIndex === i}" ${busy ? "disabled" : ""}>[${i + 1}] ${["Quick", "Medium", "Long"][i]} (${n})</button>`).join("");
  const options = [`<option value="random" ${weight === "random" ? "selected" : ""}>Random weight class</option>`, ...weights.map((n) => `<option value="${n}" ${weight === n ? "selected" : ""}>${n} kg</option>`)].join("");
  const retry = errorMessage ? `<button class="retry" data-retry>Retry ${target}-point match</button>` : "";
  return `<section class="launcher" aria-label="Match setup"><p class="eyebrow">Classic Battle</p><h2>Start a bout</h2><p>Choose a division, a game mode, and a first-to score.</p><fieldset class="mode-picker"><legend>Division</legend><label><input type="radio" name="division-mode" value="absolute" ${division === "absolute" ? "checked" : ""}/> Absolute <span>Open weight</span></label><label><input type="radio" name="division-mode" value="weight" ${division === "weight" ? "checked" : ""}/> Weight class <span>Comparable division</span></label></fieldset>${division === "weight" ? `<label class="weight-picker" for="weight-class">Weight class <select id="weight-class">${options}</select></label>` : ""}<fieldset class="mode-picker"><legend>Game mode</legend><label><input type="radio" name="game-mode" value="classic" ${mode === "classic" ? "checked" : ""}/> Top Trumps <span>Both players draw a new judoka every round.</span></label><label><input type="radio" name="game-mode" value="champion" ${mode === "champion" ? "checked" : ""}/> Champion <span>Keep your judoka and face a new opponent each round.</span></label></fieldset><h2 class="match-length-heading">Match length</h2><p>First to the selected number of points wins.</p><p class="keyboard-hint">Choose with <kbd>1</kbd>–<kbd>3</kbd> or arrow keys, then confirm.</p><div class="actions menu-actions">${select}</div><button class="primary-action" id="start" ${busy ? "disabled" : ""}>[Enter] Start bout · First to ${target}</button>${retry}${advanced()}</section>`;
}
function pips(score: number, side: "player" | "opponent"): string { return Array.from({ length: match!.target }, (_, i) => `<span class="score-pip ${side} ${i < score ? "earned" : ""} ${i === score - 1 && result?.outcome === side ? "just-earned" : ""}" aria-hidden="true"></span>`).join(""); }
function scoreboard(m: Match): string { return `<section class="scoreboard" aria-label="Match score: You ${m.scores.player}, opponent ${m.scores.opponent}. First to ${m.target} points."><div class="score-side player"><span>You</span><strong>${m.scores.player}</strong><div class="score-pips">${pips(m.scores.player, "player")}</div></div><p>First to ${m.target}</p><div class="score-side opponent"><span>Opponent</span><strong>${m.scores.opponent}</strong><div class="score-pips">${pips(m.scores.opponent, "opponent")}</div></div></section>`; }
function callout(m: Match, r: RoundResult): string { const move = { power: "a driving throw", speed: "a lightning entry", technique: "clean technique", kumikata: "a dominant grip", newaza: "a tight turnover" }[r.stat]; return r.outcome === "draw" ? `${nameOf(m.player)} and ${nameOf(m.opponent)} are evenly matched in the exchange.` : `${nameOf(r.outcome === "player" ? m.player : m.opponent)} takes the point with ${move}.`; }
function historyStrip(): string { if (!history.length) return ""; return `<section class="round-history" aria-label="Bout history"><p class="eyebrow">Bout history</p><ol>${history.map((h) => `<li class="${h.outcome}"><span>R${h.round}</span><strong>${labels[h.stat]}</strong><span>${h.outcome === "player" ? "WIN" : h.outcome === "opponent" ? "LOSS" : "DRAW"}</span></li>`).join("")}</ol></section>`; }
function game(m: Match): string {
  const stats = STAT_KEYS.map((stat, i) => `<button class="stat ${result?.stat === stat ? `selected-stat outcome-${result.outcome}` : ""} ${pendingStat === stat ? "is-committing" : ""}" data-stat="${stat}" ${m.phase !== "selecting" || busy || pendingStat ? "disabled" : ""}><span>[${i + 1}] ${labels[stat]}</span><strong>${m.player.stats[stat]}</strong></button>`).join("");
  const committing = pendingStat ? `<section class="commitment" aria-live="polite"><span class="block-cursor" aria-hidden="true">█</span><div><strong>Opponent commits…</strong><p>Resolving ${labels[pendingStat]}.</p></div></section>` : "";
  const reveal = result ? `<section class="round-result ${result.outcome}" aria-label="Round result"><strong>${result.outcome === "draw" ? "Draw" : result.outcome === "player" ? "Round won" : "Round lost"}</strong><p>You used <strong>${result.playerValue}</strong> in ${labels[result.stat]}. ${esc(nameOf(m.opponent))} had <strong>${result.opponentValue}</strong>.</p><p class="callout">${esc(callout(m, result))}</p></section>` : "";
  const action = m.phase === "awaitingNext" ? '<button id="next">[Enter] Next round</button>' : m.phase === "matchOver" ? '<button id="replay">[Enter] Play again</button>' : "";
  const opponent = result ? fighter(m.opponent, "opponent") : `<section class="fighter-card opponent concealed" aria-label="Opponent concealed"><p class="eyebrow">Opponent</p><h2>Hidden judoka</h2><p>Revealed when the round ends.</p></section>`;
  return `${scoreboard(m)}<section class="battle-layout"><div class="player-column">${fighter(m.player, "player")}<section aria-label="Stat selection" class="stats">${stats}</section>${committing}${reveal}<div class="actions game-actions">${action}<button class="quiet" id="quit">[Esc/Q] Quit match</button></div>${historyStrip()}</div>${opponent}</section>`;
}
function render(): void { const hint = !match ? "Keys: [1–3]/[←/→] Choose · [Enter] Confirm" : pendingStat ? "Keys: Resolving opponent… · [Esc/Q] Back" : match.phase === "selecting" ? "Keys: [1–5] Select stat · [Esc/Q] Back" : match.phase === "awaitingNext" ? "Keys: [Enter] Next round · [Esc/Q] Back" : "Keys: [Enter] Play again · [Esc/Q] Back"; root.innerHTML = `<header><div>bash - JU-DO-KON</div><p>${match ? `Round ${match.round} · ${modeLabel()} · ${divisionLabel()} · Target: ${match.target} · You: ${match.scores.player} · Opponent: ${match.scores.opponent}` : `${modeLabel()} · ${divisionLabel()} division · Target: ${target}`}</p></header><main id="game" tabindex="-1"><p id="status" class="active-command" role="status" aria-live="polite">${status()} <span class="block-cursor" aria-hidden="true">█</span></p>${match ? game(match) : launch()}</main><footer>${hint}</footer>`; }
function start(points = target): void { target = points; lengthIndex = lengths.indexOf(points as typeof lengths[number]); activeSeed = seed || crypto.randomUUID(); let hash = 0; for (const c of activeSeed) hash = (hash * 31 + c.charCodeAt(0)) >>> 0; activeWeight = division === "weight" ? weight === "random" ? weights[hash % weights.length] : weight : undefined; pendingStat = null; history = []; persist(); void draw(); }
function tone(frequency: number, duration: number, volume = 0.025): void {
  if (!soundEnabled) return;
  audioContext ??= new AudioContext();
  if (audioContext.state === "suspended") void audioContext.resume();
  const oscillator = audioContext.createOscillator(), gain = audioContext.createGain();
  oscillator.type = "square"; oscillator.frequency.value = frequency; gain.gain.setValueAtTime(volume, audioContext.currentTime); gain.gain.exponentialRampToValueAtTime(0.001, audioContext.currentTime + duration);
  oscillator.connect(gain).connect(audioContext.destination); oscillator.start(); oscillator.stop(audioContext.currentTime + duration);
}
function keyboardTick(): void { tone(780, 0.025, 0.014); }
function outcomeBeep(outcome: RoundResult["outcome"]): void { if (outcome === "player") { tone(880, 0.08); window.setTimeout(() => tone(1175, 0.11), 95); } else if (outcome === "opponent") tone(220, 0.16, 0.03); else tone(520, 0.1, 0.018); }
async function draw(): Promise<void> { busy = true; result = null; errorMessage = ""; render(); try { const [a, b] = await client.drawPair(activeSeed, activeWeight); match = createMatch(a, b, target, 1, { player: 0, opponent: 0 }, mode); } catch (e) { match = null; errorMessage = e instanceof Error && e.message.startsWith("No compatible") ? `${e.message}. Choose Absolute or another division.` : e instanceof Error ? `${e.message}. Check your connection and try again.` : "Unable to draw judoka. Please try again."; } finally { busy = false; render(); } }
async function next(m: Match): Promise<void> { busy = true; result = null; errorMessage = ""; render(); try { const roundSeed = `${activeSeed}:${m.round + 1}`; if (m.mode === "champion") match = nextRound(m, m.player, await client.drawOpponent(roundSeed, [m.player.id, m.opponent.id], activeWeight)); else { const [a, b] = await client.drawPair(roundSeed, activeWeight); match = nextRound(m, a, b); } } catch (e) { errorMessage = e instanceof Error ? `${e.message}. Try the next round again.` : "Unable to draw judoka. Please try again."; } finally { busy = false; render(); } }
function choose(n: number): void { target = n; lengthIndex = lengths.indexOf(n as typeof lengths[number]); render(); root.querySelector<HTMLButtonElement>(`[data-length="${n}"]`)?.focus(); }
function resolve(stat: StatKey): void { if (!match || match.phase !== "selecting" || pendingStat) return; pendingStat = stat; render(); window.setTimeout(() => { if (!match || pendingStat !== stat) return; result = selectStat(match, stat); match = result.match; history.push({ outcome: result.outcome, stat, round: match.round }); pendingStat = null; outcomeBeep(result.outcome); render(); root.querySelector<HTMLButtonElement>("#next, #replay")?.focus(); }, 650); }
root.addEventListener("click", (e) => { const b = (e.target as Element).closest<HTMLButtonElement>("button"); if (!b || b.disabled) return; if (b.dataset.length) choose(Number(b.dataset.length)); else if (b.id === "start") start(); else if (b.dataset.retry || b.id === "replay") start(); else if (b.dataset.stat) resolve(b.dataset.stat as StatKey); else if (b.id === "next" && match) void next(match); else if (b.id === "quit") { match = null; result = null; pendingStat = null; errorMessage = ""; history = []; render(); } });
root.addEventListener("input", (e) => { if ((e.target as HTMLInputElement).id === "seed") { seed = (e.target as HTMLInputElement).value.trim(); persist(); } });
root.addEventListener("change", (e) => { const input = e.target as HTMLInputElement; if (input.name === "division-mode") division = input.value === "weight" ? "weight" : "absolute"; if (input.name === "game-mode") mode = input.value === "champion" ? "champion" : "classic"; if (input.id === "weight-class") weight = input.value; if (input.id === "sound-enabled") { soundEnabled = input.checked; localStorage.setItem("judokon.soundEnabled", String(soundEnabled)); } persist(); render(); });
document.addEventListener("keydown", (e) => { if ((e.target as HTMLElement).matches("input, select")) return; if (/^[1-5]$/.test(e.key) || ["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown", "Enter", " ", "Escape"].includes(e.key) || e.key.toLowerCase() === "q") keyboardTick(); if (!match) { if (e.key >= "1" && e.key <= "3") { e.preventDefault(); choose(lengths[Number(e.key) - 1]!); } else if (e.key === "ArrowLeft" || e.key === "ArrowUp") { e.preventDefault(); choose(lengths[(lengthIndex + lengths.length - 1) % lengths.length]!); } else if (e.key === "ArrowRight" || e.key === "ArrowDown") { e.preventDefault(); choose(lengths[(lengthIndex + 1) % lengths.length]!); } else if (e.key === "Enter" || e.key === " ") { e.preventDefault(); start(); } return; } if (e.key >= "1" && e.key <= "5" && match.phase === "selecting") resolve(STAT_KEYS[Number(e.key) - 1]!); if ((e.key === "Enter" || e.key === " ") && match.phase === "awaitingNext") { e.preventDefault(); root.querySelector<HTMLButtonElement>("#next")?.click(); } if ((e.key === "Enter" || e.key === " ") && match.phase === "matchOver") { e.preventDefault(); root.querySelector<HTMLButtonElement>("#replay")?.click(); } if (e.key.toLowerCase() === "q" || e.key === "Escape") root.querySelector<HTMLButtonElement>("#quit")?.click(); });
render();
