import "./style.css";
import { BudokonClient } from "./api/budokon";
import { STAT_KEYS, type Judoka, type StatKey } from "./api/types";
import { MAX_ROUNDS, createMatch, matchSummary, nextMatch, selectStat, strongestStats, type GameMode, type Match, type MatchResult } from "./game/game";

const labels: Record<StatKey, string> = { power: "Power", speed: "Speed", technique: "Technique", kumikata: "Kumi-kata", newaza: "Ne-waza" };
const lengths = [3, 5, 10] as const;
const weights = ["-48", "-52", "-57", "-60", "-63", "-66", "-70", "-73", "-78", "-81", "-90", "-100", "+78", "+100"] as const;
type Division = "absolute" | "weight";
type History = Pick<MatchResult, "outcome" | "stat"> & { roundNumber: number };
const app = document.querySelector<HTMLDivElement>("#app");
if (!app) throw new Error("Application root is missing");
const root = app;
const client = new BudokonClient();
let match: Match | null = null, result: MatchResult | null = null, pendingStat: StatKey | null = null;
let activeSeed = "", activeWeight: string | undefined;
let target = 3, lengthIndex = 0, busy = false, errorMessage = "", history: History[] = [];
let division: Division = localStorage.getItem("judokon.divisionMode") === "weight" ? "weight" : "absolute";
let mode: GameMode = localStorage.getItem("judokon.gameMode") === "champion" ? "champion" : "classic";
let weight = localStorage.getItem("judokon.weightClass") ?? "random";
let soundEnabled = localStorage.getItem("judokon.soundEnabled") === "true";
let audioContext: AudioContext | null = null;

const esc = (value: string) => { const e = document.createElement("span"); e.textContent = value; return e.innerHTML; };
const nameOf = (j: Judoka) => `${j.firstname} ${j.surname}`;
const detailOf = (j: Judoka) => `${j.country} · ${j.weightClass} kg`;
const divisionLabel = () => division === "absolute" ? "Absolute" : weight === "random" ? "Random weight" : `${weight} kg`;
const modeLabel = () => mode === "champion" ? "Champion" : "Classic Battle";
const eyebrow = (label: string) => `<p class="eyebrow">${esc(label)}</p>`;
function persist(): void { localStorage.setItem("judokon.divisionMode", division); localStorage.setItem("judokon.gameMode", mode); localStorage.setItem("judokon.weightClass", weight); }
function status(): string {
  if (busy) return ">> Drawing judoka…"; if (errorMessage) return `>> ${errorMessage}`; if (!match) return ">> Configure a division and select a match length.";
  if (pendingStat) return ">> Opponent commits…"; if (match.phase === "selecting") return ">> Choose your stat:";
  if (match.phase === "matchOver") return `>> ${match.winner === "draw" ? "Match drawn." : match.winner === "player" ? "You win the match!" : "Opponent wins the match."}`;
  if (!result) return ">> Match resolved."; return `>> ${result.outcome === "draw" ? "No point awarded" : result.outcome === "player" ? "You take the point" : "Opponent takes the point"}: ${labels[result.stat]} ${result.playerValue}–${result.opponentValue}.`;
}
function fighter(j: Judoka, side: "player" | "opponent", comparison = result): string {
  const label = side === "player" ? "Your judoka" : "Opponent", value = comparison ? side === "player" ? comparison.playerValue : comparison.opponentValue : null;
  const chosen = comparison ? `<p class="selected-stat outcome-${comparison.outcome}"><span>${labels[comparison.stat]}</span><strong>${value}</strong></p>` : "";
  const rarity = j.rarity || "Unclassified";
  return `<section class="fighter-card ${side}" aria-label="${label}: ${esc(nameOf(j))}">${eyebrow(label)}<h2>${esc(nameOf(j))}</h2><p>${esc(detailOf(j))}</p>${chosen}<span class="badge rarity rarity-${esc(rarity.toLowerCase())}">${esc(rarity)}</span></section>`;
}
function shortcutHint(keys: string): string { return `<span class="badge shortcut-hint" aria-hidden="true"><kbd>${esc(keys)}</kbd></span>`; }
function primaryButton(id: string, label: string, shortcut: string, disabled = false): string { return `<button class="action-button primary-action" id="${id}" ${disabled ? "disabled" : ""}><span>${esc(label)}</span>${shortcutHint(shortcut)}</button>`; }
function optionCard(label: string, shortcut: string, value: string, data: string, pressed: boolean, disabled: boolean, selected = false, strongest = false): string { return `<button class="action-button option-card ${selected ? "is-selected" : ""} ${strongest ? "is-strongest" : ""}" ${data} aria-pressed="${pressed}" ${disabled ? "disabled" : ""}><span>${esc(label)}</span><strong>${esc(value)}</strong>${strongest ? `<em>Strongest</em>` : ""}${shortcutHint(shortcut)}</button>`; }
function quietButton(id: string, label: string, shortcut: string): string { return `<button class="action-button quiet" id="${id}"><span>${esc(label)}</span>${shortcutHint(shortcut)}</button>`; }
function toggle(id: string, label: string, checked: boolean, description: string): string { return `<label class="toggle-control" for="${id}"><span><strong>${esc(label)}</strong><small>${esc(description)}</small></span><input id="${id}" type="checkbox" role="switch" ${checked ? "checked" : ""} /><span class="toggle-state" aria-hidden="true">${checked ? "On" : "Off"}</span></label>`; }
function advanced(): string { return `<details class="advanced"><summary aria-label="Show advanced options"><span>Advanced options</span><span class="disclosure-state" aria-hidden="true">Show</span></summary><div class="advanced-content">${toggle("sound-enabled", "Sound", soundEnabled, "Keyboard ticks and outcome beeps")}</div></details>`; }
function intro(): string {
  const divisionOptions = optionCard("Absolute", "A", "Open weight", `data-division="absolute"`, division === "absolute", false)
    + optionCard("Weight class", "W", "Comparable division", `data-division="weight"`, division === "weight", false);
  const modeOptions = optionCard("Classic Battle", "C", "Fresh matchups", `data-intro-mode="classic"`, mode === "classic", false)
    + optionCard("Champion", "H", "Build a streak", `data-intro-mode="champion"`, mode === "champion", false);
  const select = lengths.map((n, i) => optionCard(["Quick", "Medium", "Long"][i]!, String(i + 1), `First to ${n}`, `data-length="${n}"`, lengthIndex === i, busy)).join("");
  const options = [`<option value="random" ${weight === "random" ? "selected" : ""}>Random weight class</option>`, ...weights.map((n) => `<option value="${n}" ${weight === n ? "selected" : ""}>${n} kg</option>`)].join("");
  const description = mode === "champion" ? "Keep one judoka in the fight and build a streak against new opponents." : "Draw a fresh judoka matchup every round and choose the best exchange.";
  return `<section class="intro" aria-labelledby="intro-title"><div class="intro-copy"><p class="eyebrow">Budokon terminal · 2600</p><h1 id="intro-title">Enter the<br/>judoka circuit.</h1><p class="intro-lede">Choose your format, then read the opponent and build a run one point at a time.</p><p class="intro-status" role="status">System ready. Configure your match<span class="block-cursor" aria-hidden="true">█</span></p></div><section class="intro-mode-panel panel" aria-label="Match setup">${eyebrow("Match setup")}<h2>Set the terms</h2><div class="setup-group"><p>Division</p><div class="actions intro-mode-actions">${divisionOptions}</div>${division === "weight" ? `<label class="weight-picker" for="weight-class">Weight class <select id="weight-class">${options}</select></label>` : ""}</div><div class="setup-group"><p>Game mode</p><div class="actions intro-mode-actions">${modeOptions}</div><small>${description}</small></div><div class="setup-group"><p>Match length</p><div class="actions intro-mode-actions length-actions">${select}</div></div><aside class="panel match-rules" aria-label="Match rules"><strong>Match rules</strong><p>Higher stat wins a point; draws score no points. After ${MAX_ROUNDS} rounds, the leading score wins—or the match is drawn.</p></aside>${primaryButton("start", `Start match · First to ${target}`, "Enter", busy)}${advanced()}</section><p class="intro-footnote">Use <kbd>A</kbd>/<kbd>W</kbd> for division · <kbd>C</kbd>/<kbd>H</kbd> for mode · <kbd>1–3</kbd> for length · <kbd>Enter</kbd> to start</p></section>`;
}
function pips(score: number, side: "player" | "opponent"): string { return Array.from({ length: match!.target }, (_, i) => `<span class="score-pip ${side} ${i < score ? "earned" : ""} ${i === score - 1 && result?.outcome === side ? "just-earned" : ""}" aria-hidden="true"></span>`).join(""); }
function scoreboard(m: Match): string { return `<section class="scoreboard" aria-label="Match score: You ${m.scores.player}, opponent ${m.scores.opponent}. First to ${m.target} points."><div class="score-side player"><span>You</span><strong>${m.scores.player}</strong><div class="score-pips">${pips(m.scores.player, "player")}</div></div><p>First to ${m.target}</p><div class="score-side opponent"><span>Opponent</span><strong>${m.scores.opponent}</strong><div class="score-pips">${pips(m.scores.opponent, "opponent")}</div></div></section>`; }
function callout(m: Match, r: MatchResult): string { const move = { power: "a driving throw", speed: "a lightning entry", technique: "clean technique", kumikata: "a dominant grip", newaza: "a tight turnover" }[r.stat]; return r.outcome === "draw" ? `${nameOf(m.player)} and ${nameOf(m.opponent)} are evenly matched in the exchange.` : `${nameOf(r.outcome === "player" ? m.player : m.opponent)} takes the point with ${move}.`; }
function historyStrip(): string { if (!history.length) return ""; return `<section class="match-history" aria-label="Round history">${eyebrow("Round history")}<ol>${history.map((h) => `<li class="${h.outcome}"><span>R${h.roundNumber}</span><strong>${labels[h.stat]}</strong><span>${h.outcome === "player" ? "WIN" : h.outcome === "opponent" ? "LOSS" : "DRAW"}</span></li>`).join("")}</ol></section>`; }
function championProgress(m: Match): string {
  if (m.mode !== "champion") return "";
  const details = matchSummary(m, history), record = details.championRecord!;
  const streak = details.championStreak ?? 0;
  return `<section class="panel champion-progress" aria-label="Champion run progress">${eyebrow("Champion run")}<dl><div><dt>Current streak</dt><dd>${streak} ${streak === 1 ? "win" : "wins"}</dd></div><div><dt>Record</dt><dd>${record.wins}–${record.losses}–${record.draws}</dd></div><div><dt>Opponents faced</dt><dd>${m.matchNumber}</dd></div></dl></section>`;
}
function summary(m: Match): string { if (m.phase !== "matchOver") return ""; const details = matchSummary(m, history); const progress = m.mode === "champion" ? `Run record: ${details.championRecord!.wins}–${details.championRecord!.losses}–${details.championRecord!.draws}` : `Points won: ${details.playerWins}`; const bestChoice = details.bestStat ? `${labels[details.bestStat]} · ${details.bestStatWins}/${details.bestStatSelections} ${details.bestStatWins === 1 ? "win" : "wins"}` : "No winning choice"; return `<section class="panel match-summary" aria-label="Match summary">${eyebrow("Match summary")}<dl><div><dt>Final score</dt><dd>${details.score}</dd></div><div><dt>Most used stat</dt><dd>${details.decisiveStat ? labels[details.decisiveStat] : "—"}</dd></div><div><dt>Best choice</dt><dd>${bestChoice}</dd></div><div><dt>${m.mode === "champion" ? "Champion progress" : "Match progress"}</dt><dd>${progress}</dd></div></dl></section>`; }
function resultPanel(m: Match, r: MatchResult): string {
  const title = m.phase === "matchOver" ? r.outcome === "draw" ? "MATCH DRAWN" : r.outcome === "player" ? "MATCH WON" : "MATCH LOST" : r.outcome === "draw" ? "NO POINT AWARDED" : r.outcome === "player" ? "POINT WON" : "POINT LOST";
  return `<section class="panel result-panel outcome-${r.outcome}" aria-label="Round result">${eyebrow(title)}<p>You used <strong>${r.playerValue}</strong> in ${labels[r.stat]}. ${esc(nameOf(m.opponent))} had <strong>${r.opponentValue}</strong>.</p><p class="callout">${esc(callout(m, r))}</p></section>`;
}
function game(m: Match): string {
  const playerStrengths = strongestStats(m.player);
  const stats = STAT_KEYS.map((stat, i) => optionCard(labels[stat], String(i + 1), String(m.player.stats[stat]), `data-stat="${stat}"`, false, m.phase !== "selecting" || busy || Boolean(pendingStat), result?.stat === stat || pendingStat === stat, playerStrengths.includes(stat))).join("");
  const committing = pendingStat ? `<section class="commitment" aria-live="polite"><span class="block-cursor" aria-hidden="true">█</span><div><strong>Opponent commits…</strong><p>Resolving ${labels[pendingStat]}.</p></div></section>` : "";
  const reveal = result ? `${resultPanel(m, result)}${summary(m)}` : "";
  const action = m.phase === "awaitingNext" ? primaryButton("next", "Next round", "Enter") : m.phase === "matchOver" ? primaryButton("replay", "Play again", "Enter") : "";
  const scout = result ? "" : `<aside class="panel scout-report" aria-label="Scout report">${eyebrow("Scout report")}<p>Opponent's likely strength: <strong>${strongestStats(m.opponent).map((stat) => labels[stat]).join(" / ")}</strong>. Choose your exchange carefully.</p></aside>`;
  const opponent = result ? fighter(m.opponent, "opponent") : `<section class="fighter-card opponent concealed" aria-label="Opponent concealed">${eyebrow("Opponent")}<h2>Hidden judoka</h2><p>Revealed after your selection.</p></section>${scout}`;
  return `${scoreboard(m)}<section class="battle-layout"><div class="player-column">${fighter(m.player, "player")}${championProgress(m)}<section aria-label="Stat selection" class="stats">${stats}</section>${committing}${reveal}<div class="actions game-actions">${action}${quietButton("quit", m.phase === "matchOver" ? "Change settings" : "Quit match", "Esc / Q")}</div>${historyStrip()}</div>${opponent}</section>`;
}
function render(): void { const hint = !match ? `${shortcutHint("A / W")} Division ${shortcutHint("1–3")} Length ${shortcutHint("Enter")} Start` : pendingStat ? "Resolving opponent…" : match.phase === "selecting" ? `${shortcutHint("1–5")} Choose a stat ${shortcutHint("Esc / Q")} Quit match` : match.phase === "awaitingNext" ? `${shortcutHint("Enter")} Next round ${shortcutHint("Esc / Q")} Quit match` : `${shortcutHint("Enter")} Play again ${shortcutHint("Esc / Q")} Change settings`; const content = !match ? intro() : `<p id="status" class="active-command" role="status" aria-live="polite">${status()} <span class="block-cursor" aria-hidden="true">█</span></p>${game(match)}`; root.innerHTML = `<header><div>bash - JU-DO-KON</div><p>${match ? `Round ${match.matchNumber} · ${modeLabel()} · ${divisionLabel()} · First to ${match.target} · You: ${match.scores.player} · Opponent: ${match.scores.opponent}` : `${modeLabel()} · ${divisionLabel()} division · First to ${target}`}</p></header><main id="game" tabindex="-1" class="${!match ? "intro-main" : ""}">${content}</main><footer><span class="footer-hint">${hint}</span></footer>`; }
function start(points = target): void { target = points; lengthIndex = lengths.indexOf(points as typeof lengths[number]); activeSeed = crypto.randomUUID(); let hash = 0; for (const c of activeSeed) hash = (hash * 31 + c.charCodeAt(0)) >>> 0; activeWeight = division === "weight" ? weight === "random" ? weights[hash % weights.length] : weight : undefined; pendingStat = null; history = []; persist(); void draw(); }
function tone(frequency: number, duration: number, volume = 0.025): void {
  if (!soundEnabled) return;
  audioContext ??= new AudioContext();
  if (audioContext.state === "suspended") void audioContext.resume();
  const oscillator = audioContext.createOscillator(), gain = audioContext.createGain();
  oscillator.type = "square"; oscillator.frequency.value = frequency; gain.gain.setValueAtTime(volume, audioContext.currentTime); gain.gain.exponentialRampToValueAtTime(0.001, audioContext.currentTime + duration);
  oscillator.connect(gain).connect(audioContext.destination); oscillator.start(); oscillator.stop(audioContext.currentTime + duration);
}
function keyboardTick(): void { tone(780, 0.025, 0.014); }
function outcomeBeep(outcome: MatchResult["outcome"]): void { if (outcome === "player") { tone(880, 0.08); window.setTimeout(() => tone(1175, 0.11), 95); } else if (outcome === "opponent") tone(220, 0.16, 0.03); else tone(520, 0.1, 0.018); }
async function draw(): Promise<void> { busy = true; result = null; errorMessage = ""; render(); try { const [a, b] = await client.drawPair(activeSeed, activeWeight); match = createMatch(a, b, target, 1, { player: 0, opponent: 0 }, mode); } catch (e) { match = null; errorMessage = e instanceof Error && e.message.startsWith("No compatible") ? `${e.message}. Choose Absolute or another division.` : e instanceof Error ? `${e.message}. Check your connection and try again.` : "Unable to draw judoka. Please try again."; } finally { busy = false; render(); } }
async function next(m: Match): Promise<void> { busy = true; result = null; errorMessage = ""; render(); try { const matchSeed = `${activeSeed}:${m.matchNumber + 1}`; if (m.mode === "champion") match = nextMatch(m, m.player, await client.drawOpponent(matchSeed, [m.player.id, m.opponent.id], activeWeight)); else { const [a, b] = await client.drawPair(matchSeed, activeWeight); match = nextMatch(m, a, b); } } catch (e) { errorMessage = e instanceof Error ? `${e.message}. Try the next match again.` : "Unable to draw judoka. Please try again."; } finally { busy = false; render(); } }
function choose(n: number): void { target = n; lengthIndex = lengths.indexOf(n as typeof lengths[number]); render(); root.querySelector<HTMLButtonElement>(`[data-length="${n}"]`)?.focus(); }
function resolve(stat: StatKey): void { if (!match || match.phase !== "selecting" || pendingStat) return; pendingStat = stat; render(); window.setTimeout(() => { if (!match || pendingStat !== stat) return; result = selectStat(match, stat); match = result.match; history.push({ outcome: result.outcome, stat, roundNumber: match.matchNumber }); pendingStat = null; outcomeBeep(result.outcome); render(); root.querySelector<HTMLButtonElement>("#next, #replay")?.focus(); }, 650); }
root.addEventListener("click", (e) => { const b = (e.target as Element).closest<HTMLButtonElement>("button"); if (!b || b.disabled) return; if (b.dataset.division) { division = b.dataset.division === "weight" ? "weight" : "absolute"; persist(); render(); root.querySelector<HTMLButtonElement>(`[data-division="${division}"]`)?.focus(); } else if (b.dataset.introMode) { mode = b.dataset.introMode === "champion" ? "champion" : "classic"; persist(); render(); root.querySelector<HTMLButtonElement>(`[data-intro-mode="${mode}"]`)?.focus(); } else if (b.dataset.length) choose(Number(b.dataset.length)); else if (b.id === "start") start(); else if (b.id === "retry" || b.id === "replay") start(); else if (b.dataset.stat) resolve(b.dataset.stat as StatKey); else if (b.id === "next" && match) void next(match); else if (b.id === "quit") { match = null; result = null; pendingStat = null; errorMessage = ""; history = []; render(); } });
root.addEventListener("change", (e) => { const input = e.target as HTMLInputElement; if (input.id === "weight-class") weight = input.value; if (input.id === "sound-enabled") { soundEnabled = input.checked; localStorage.setItem("judokon.soundEnabled", String(soundEnabled)); } persist(); render(); });
root.addEventListener("toggle", (e) => { const details = e.target; if (!(details instanceof HTMLDetailsElement) || !details.matches(".advanced")) return; const summary = details.querySelector("summary"), state = details.querySelector(".disclosure-state"); if (summary) summary.setAttribute("aria-label", `${details.open ? "Hide" : "Show"} advanced options`); if (state) state.textContent = details.open ? "Hide" : "Show"; }, true);
document.addEventListener("keydown", (e) => { if ((e.target as HTMLElement).matches("input, select")) return; if (/^[1-5]$/.test(e.key) || ["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown", "Enter", " ", "Escape"].includes(e.key) || ["a", "w", "c", "h", "q"].includes(e.key.toLowerCase())) keyboardTick(); if (!match) { if (e.key >= "1" && e.key <= "3") { e.preventDefault(); choose(lengths[Number(e.key) - 1]!); } else if (e.key.toLowerCase() === "a" || e.key.toLowerCase() === "w") { e.preventDefault(); root.querySelector<HTMLButtonElement>(`[data-division="${e.key.toLowerCase() === "w" ? "weight" : "absolute"}"]`)?.click(); } else if (e.key.toLowerCase() === "c" || e.key.toLowerCase() === "h") { e.preventDefault(); root.querySelector<HTMLButtonElement>(`[data-intro-mode="${e.key.toLowerCase() === "h" ? "champion" : "classic"}"]`)?.click(); } else if (e.key === "ArrowLeft" || e.key === "ArrowUp") { e.preventDefault(); choose(lengths[(lengthIndex + lengths.length - 1) % lengths.length]!); } else if (e.key === "ArrowRight" || e.key === "ArrowDown") { e.preventDefault(); choose(lengths[(lengthIndex + 1) % lengths.length]!); } else if (e.key === "Enter" || e.key === " ") { e.preventDefault(); start(); } return; } if (e.key >= "1" && e.key <= "5" && match.phase === "selecting") resolve(STAT_KEYS[Number(e.key) - 1]!); if ((e.key === "Enter" || e.key === " ") && match.phase === "awaitingNext") { e.preventDefault(); root.querySelector<HTMLButtonElement>("#next")?.click(); } if ((e.key === "Enter" || e.key === " ") && match.phase === "matchOver") { e.preventDefault(); root.querySelector<HTMLButtonElement>("#replay")?.click(); } if (e.key.toLowerCase() === "q" || e.key === "Escape") root.querySelector<HTMLButtonElement>("#quit")?.click(); });
render();
