name: Workflow Lint

on:
  pull_request:
    paths:
      - .github/workflows/**
  push:
    branches: [main]
    paths:
      - .github/workflows/**

permissions:
  contents: read
  checks: write

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: reviewdog/action-actionlint@13465d022aa41c282f730be17574b5ce692d0186 # v1.78.1
        with:
          reporter: github-check
          fail_level: error
